# Python helper file/script for MATLAB

This cell sets up the notebook to import numpy, datascience, seaborn, pandas, matplotlib etc.

In [20]:
# Run this cell to set up the notebook.

# These lines import the Numpy, Datascience, pandas modules.
import numpy as np
import pandas as pd
import seaborn as sns
from datascience import *
import random
import matplotlib
import matplotlib.pyplot as plt

# Importing plotting libraries and styles
%matplotlib inline
plt.style.use('fivethirtyeight')

# For Pandas to ignore FutureWarning displays
import warnings
warnings.simplefilter('ignore', FutureWarning)

### The cell given below sets up MATLAB for the notebook
Source: https://sehyoun.com/blog/20180904_using-matlab-with-jupyter-notebook.html

In [21]:
import matlab.engine
import io
import scipy.io
from IPython.core.magic import register_cell_magic
ip = get_ipython()

out = io.StringIO()
err = io.StringIO()

# Setup matlab cell magic #
@register_cell_magic
def matlab_magic(line,cell):
    out.truncate(0)
    out.seek(0)
    err.truncate(0)
    err.truncate(0)
    raw = '''{line}.eval("""{cell}""", nargout=0, stdout=out, stderr=err)'''
    ip.run_cell(raw.format(line=line, cell=cell))
    print(out.getvalue())
    print(err.getvalue())
    
# Starting a MATLAB engine called eng
eng = matlab.engine.start_matlab()

In [22]:
%%matlab_magic eng

t = linspace(0,6*pi,100);
plot(sin(t))
grid on
hold on
plot(cos(t), 'r')

In [23]:
%%matlab_magic eng

x = 5;
disp(x);
x

     5


x =

     5





Calling another MATLAB file from Python script

In [24]:
%%matlab_magic eng

my_array = [10, 20, 30, 40, 50]
avgOfThis = averageFunc(my_array)


my_array =

    10    20    30    40    50


avgOfThis =

    30





**Python to MATLAB**

Source: https://stackoverflow.com/questions/10997254/converting-numpy-arrays-to-matlab-and-vice-versa

In [25]:
x = [1,2,3]
y = "hello"
z = [[1,2,3], [4,5,6]]

scipy.io.savemat('test.mat', dict(x=x, y=y, z=z))

In [26]:
%%matlab_magic eng
load test
x
y
z


x =

  1x3 int64 row vector

   1   2   3


y =

    'hello'


z =

  2x3 int64 matrix

   1   2   3
   4   5   6





**MATLAB to Python**

Source: http://www.blogforbrains.com/blog/2014/9/6/loading-matlab-mat-data-in-python

In [27]:
# Similarly we have
#scipy.io.loadmat("averageFunc.m")
variables = scipy.io.loadmat('data.mat', squeeze_me=True)
variables

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Fri Feb  8 01:20:47 2019',
 '__version__': '1.0',
 '__globals__': [],
 'a': array([[1, 2, 3],
        [4, 5, 6]], dtype=uint8),
 'S': array((array([[ 7,  8,  9],
        [10, 11, 12]], dtype=uint8),), dtype=[('b', 'O')]),
 'M': array([(array([[ 2,  4,  6],
        [ 8, 10, 12]], dtype=uint8),),
        (array([[ 1,  3,  5],
        [ 7,  9, 11]], dtype=uint8),)], dtype=[('c', 'O')])}

In [28]:
a = variables['a'] # array
S = variables['S'] # structure containing an array
M = variables['M'] # array of structures

a

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [29]:
S

array((array([[ 7,  8,  9],
       [10, 11, 12]], dtype=uint8),), dtype=[('b', 'O')])

In [30]:
M

array([(array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=uint8),),
       (array([[ 1,  3,  5],
       [ 7,  9, 11]], dtype=uint8),)], dtype=[('c', 'O')])

In [31]:
# Adds the MMB.m as well as MMBOPT1.m and MMBOPT2.m folders to the MATLAB engine path"
eng.addpath(r'/Users/Desktop/monetaryPolicy/mmb-gui-mlab/2.3.2', nargout=0)
eng.addpath(r'/Users/Desktop/monetaryPolicy/mmb-gui-mlab/2.3.2/MMB_OPTIONS', nargout=0)

**Important:** The cell below runs MMB.m

In [114]:
eng.MMB(nargout = 0)

### Here we import the data for ALL IRF (Impulse Response Functions) variables

In [38]:
old_df = pd.read_excel("../mmb-gui-mlab-2.3.2/OUTPUT/results.xls", sheetname = "all IRFs Mon. Pol. Shock")

In [113]:
df = old_df.T
new_header = df.iloc[0] # grab the first row for the header
df = df[1:] # take the data less the header row
stripped_headers = [myHeader.strip() for myHeader in np.array(new_header)] # removing trailing whitespaces
df.columns = stripped_headers # set the header row as the df header
df["c_t"] = df.index
df.index = np.arange(0,21,1)
df.index.name = "Period"

# This section rearranges the columns
n = len(list(df.columns.values))
rearranged = [list(df.columns.values)[-1]] + list(df.columns.values)[:n-1]
df = df[rearranged]
df

c_t     wtilde_t lambda_zstar_t          m_t         pi_t  \
Period                                                                      
0                 0            0              0            0            0   
1        -0.0484745  -0.00699479    -0.00019142  -0.00640682   0.00640682   
2        -0.0359882   -0.0057628     0.00374196    -0.628739   0.00458512   
3        -0.0273793  -0.00484467     0.00441633   -0.0444382   0.00327421   
4        -0.0209604  -0.00410564     0.00267624   -0.0389977   0.00230403   
5        -0.0157588  -0.00345112     0.00152936   -0.0346907   0.00154005   
6        -0.0116265  -0.00288615    0.000758499   -0.0253409  0.000956398   
7       -0.00839697  -0.00240694    0.000250941    -0.018096  0.000523723   
8       -0.00591378  -0.00200589   -5.71195e-05   -0.0124966  0.000213718   
9       -0.00403962  -0.00167413   -0.000220274  -0.00820929  1.12526e-06   
10      -0.00265503  -0.00140234   -0.000282631  -0.00500944  -0.00013601   
11      -0.00165751  -0.00118138   -0.000278614  -0.00269007 -0.000216286   
12     -0.000960579   -0.0010027   -0.000234346  -0.00106834 -0.000255067   
13     -0.000492393 -0.000858609   -0.000169017  1.27267e-05 -0.000264743   
14     -0.000194324 -0.000742384   -9.61717e-05  0.000684992 -0.000255058   
15     -1.93761e-05 -0.000648298    -2.4889e-05   0.00105686  -0.00023347   
16      6.93983e-05 -0.000571579     3.9191e-05   0.00121552  -0.00020552   
17      0.000100441 -0.000508337    9.29927e-05   0.00122949 -0.000175175   
18      9.51303e-05 -0.000455465    0.000135284   0.00115135 -0.000145149   
19      6.90965e-05 -0.000410527    0.000166095   0.00102029  -0.00011718   
20      3.33862e-05 -0.000371653    0.000186269  0.000864609 -9.22691e-05   

                x_t          s_t          i_t          h_t      kbar_t1  \
Period                                                                    
0                 0            0            0            0            0   
1         -0.617748     0.204864  -0.00435076  -0.00772508  -0.00013688   
2          0.587575   -0.0129795  -0.00799692    -0.042797 -0.000384165   
3        0.00774458  -0.00867639  -0.00999072   -0.0337628 -0.000686397   
4        0.00584697  -0.00528293   -0.0102847   -0.0264263  -0.00098837   
5         0.0103063  -0.00460463  -0.00952427    -0.020475  -0.00125692   
6        0.00776854  -0.00384489  -0.00816057   -0.0153676  -0.00147411   
7        0.00581319  -0.00311633  -0.00651357   -0.0111004  -0.00163266   
8         0.0042884  -0.00246846  -0.00480617  -0.00762111   -0.0017325   
9        0.00306383  -0.00190703  -0.00318466  -0.00485157  -0.00177819   
10       0.00210309  -0.00143277  -0.00173704  -0.00270409  -0.00177689   
11       0.00136667  -0.00104193 -0.000508289  -0.00108797  -0.00173698   
12      0.000816322  -0.00072759  0.000487096   8.5213e-05  -0.00166701   
13      0.000417207 -0.000481044   0.00125518  0.000898015  -0.00157508   
14      0.000138399 -0.000292837   0.00181495    0.0014248  -0.00146842   
15      -4.6864e-05 -0.000153511   0.00219252   0.00173058  -0.00135325   
16     -0.000161199 -5.41101e-05   0.00241701   0.00187069  -0.00123463   
17     -0.000223294   1.3498e-05   0.00251765   0.00189103  -0.00111658   
18      -0.00024824  5.64535e-05    0.0025219   0.00182873  -0.00100211   
19     -0.000247949  8.08434e-05   0.00245434   0.00171308 -0.000893365   
20     -0.000231586  9.17195e-05   0.00233613   0.00156654 -0.000791761   

              ...        AUX_ENDO_LAG_45_3 AUX_ENDO_LAG_44_1  \
Period        ...                                              
0             ...                        0                 0   
1             ...                        0                 0   
2             ...                        0       -0.00475476   
3             ...                        0        -0.0277619   
4             ...              -0.00475476        -0.0219998   
5             ...               -0.0277619        -0.0173575   
6     

Todo:
* Pull important variables of the IRF (file 1) using *selective row dataframe read*
* Use the same technique to get the Autocorrelation functions, in sheetname *ACF*

### Here we import the data for 4 IRF (Impulse Response Functions) variables
#### outputgap, inflation, interest, output

In [131]:
irf_4 = pd.read_excel("../mmb-gui-mlab-2.3.2/OUTPUT/results.xls", sheetname = "IRF Mon. Pol. Shock      ")
irf_4 = irf_4.T
irf_headers = irf_4.iloc[0] # grab the first row for the header
irf_4 = irf_4[1:] # take the data less the header row
irf_4_stripped_headers = [myHeader.strip() for myHeader in np.array(irf_headers)] # removing trailing whitespaces
irf_4.columns = irf_4_stripped_headers
modelName = irf_4.columns.values[1]
irf_4

outputgap     US_ACELm inflation     US_ACELm interest  \
Unnamed: 1        NaN            0       NaN            0      NaN   
Unnamed: 2        NaN    0.0311337       NaN  2.86822e-17      NaN   
Unnamed: 3        NaN  2.18432e-16       NaN -3.81229e-17      NaN   
Unnamed: 4        NaN  2.22032e-16       NaN  4.76894e-16      NaN   
Unnamed: 5        NaN  2.60732e-17       NaN   1.9386e-17      NaN   
Unnamed: 6        NaN  8.07435e-18       NaN  -1.4001e-16      NaN   
Unnamed: 7        NaN  4.42224e-17       NaN  -5.6088e-17      NaN   
Unnamed: 8        NaN  8.86776e-17       NaN -1.76476e-16      NaN   
Unnamed: 9        NaN  1.36262e-16       NaN -2.63726e-16      NaN   
Unnamed: 10       NaN  1.78275e-16       NaN -3.24107e-16      NaN   
Unnamed: 11       NaN  2.11565e-16       NaN -3.64082e-16      NaN   
Unnamed: 12       NaN  2.35391e-16       NaN -3.87037e-16      NaN   
Unnamed: 13       NaN  2.50207e-16       NaN -3.96556e-16      NaN   
Unnamed: 14       NaN  2.57081e-16       NaN -3.95887e-16      NaN   
Unnamed: 15       NaN  2.57351e-16       NaN -3.87821e-16      NaN   
Unnamed: 16       NaN  2.52406e-16       NaN -3.74674e-16      NaN   
Unnamed: 17       NaN  2.43565e-16       NaN -3.58306e-16      NaN   
Unnamed: 18       NaN  2.31996e-16       NaN -3.40158e-16      NaN   
Unnamed: 19       NaN  2.18694e-16       NaN -3.21308e-16      NaN   
Unnamed: 20       NaN  2.04468e-16       NaN  -3.0253e-16      NaN   
Unnamed: 21       NaN  1.89949e-16       NaN  -2.8435e-16      NaN   

                US_ACELm output     US_ACELm  
Unnamed: 1             0    NaN            0  
Unnamed: 2       1.01557    NaN    0.0311337  
Unnamed: 3   3.70087e-16    NaN  1.02879e-16  
Unnamed: 4   8.16841e-16    NaN -5.71252e-17  
Unnamed: 5   9.71128e-18    NaN  7.14301e-18  
Unnamed: 6  -2.04803e-16    NaN  7.81423e-17  
Unnamed: 7  -3.26818e-17    NaN  1.52996e-16  
Unnamed: 8  -2.20375e-16    NaN  2.17247e-16  
Unnamed: 9  -3.27458e-16    NaN    2.766e-16  
Unnamed: 10 -3.97023e-16    NaN  3.26361e-16  
Unnamed: 11  -4.4034e-16    NaN  3.64976e-16  
Unnamed: 12  -4.6286e-16    NaN  3.92427e-16  
Unnamed: 13 -4.69731e-16    NaN  4.09553e-16  
Unnamed: 14  -4.6529e-16    NaN   4.1767e-16  
Unnamed: 15 -4.53056e-16    NaN  4.18293e-16  
Unnamed: 16 -4.35808e-16    NaN  4.12957e-16  
Unnamed: 17 -4.15677e-16    NaN  4.03095e-16  
Unnamed: 18  -3.9424e-16    NaN  3.89979e-16  
Unnamed: 19 -3.72616e-16    NaN  3.74688e-16  
Unnamed: 20 -3.51562e-16    NaN  3.58107e-16  
Unnamed: 21  -3.3155e-16    NaN  3.40929e-16