# Python helper file/script for MATLAB

This cell sets up the notebook to import numpy, datascience, seaborn, pandas, matplotlib etc.

In [48]:
# Run this cell to set up the notebook.

# These lines import the Numpy, Datascience, pandas modules.
import numpy as np
import pandas as pd
import seaborn as sns
from datascience import *
import random
import matplotlib
import matplotlib.pyplot as plt

# Importing plotting libraries and styles
%matplotlib inline
plt.style.use('fivethirtyeight')

# For Pandas to ignore FutureWarning displays
import warnings
warnings.simplefilter('ignore', FutureWarning)

### The cell given below sets up MATLAB for the notebook
Source: https://sehyoun.com/blog/20180904_using-matlab-with-jupyter-notebook.html

In [49]:
import matlab.engine
import io
import scipy.io
from IPython.core.magic import register_cell_magic
ip = get_ipython()

out = io.StringIO()
err = io.StringIO()

# Setup matlab cell magic #
@register_cell_magic
def matlab_magic(line,cell):
    out.truncate(0)
    out.seek(0)
    err.truncate(0)
    err.truncate(0)
    raw = '''{line}.eval("""{cell}""", nargout=0, stdout=out, stderr=err)'''
    ip.run_cell(raw.format(line=line, cell=cell))
    print(out.getvalue())
    print(err.getvalue())
    
# Starting a MATLAB engine called eng
eng = matlab.engine.start_matlab()

Exception ignored in: <bound method MatlabEngine.__del__ of <matlab.engine.matlabengine.MatlabEngine object at 0x1a1deeb358>>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 250, in __del__
    self.exit()
  File "/anaconda3/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 232, in exit
    pythonengine.closeMATLAB(self.__dict__["_matlab"])
SystemError: MATLAB process cannot be terminated.


In [50]:
%%matlab_magic eng

t = linspace(0,6*pi,100);
plot(sin(t))
grid on
hold on
plot(cos(t), 'r')

In [51]:
%%matlab_magic eng

x = 5;
disp(x);
x

     5


x =

     5





Calling another MATLAB file from Python script

In [60]:
# Adds the MMB.m folder to the MATLAB engine path
eng.addpath(r"/Users/Desktop/monetaryPolicy/mmb-gui-mlab/2.3.2", nargout=0)
eng.addpath(r"/Users/Desktop/monetaryPolicy/mmb-gui-mlab/2.3.2/MMB_OPTIONS", nargout=0)

In [59]:
eng.MMB(nargout=0)

In [54]:
%%matlab_magic eng

my_array = [10, 20, 30, 40, 50]
avgOfThis = averageFunc(my_array)


my_array =

    10    20    30    40    50


avgOfThis =

    30





**Python to MATLAB**

Source: https://stackoverflow.com/questions/10997254/converting-numpy-arrays-to-matlab-and-vice-versa

In [6]:
x = [1,2,3]
y = "hello"
z = [[1,2,3], [4,5,6]]

scipy.io.savemat('test.mat', dict(x=x, y=y, z=z))

In [7]:
%%matlab_magic eng
load test
x
y
z


x =

  1x3 int64 row vector

   1   2   3


y =

    'hello'


z =

  2x3 int64 matrix

   1   2   3
   4   5   6





**MATLAB to Python**

Source: http://www.blogforbrains.com/blog/2014/9/6/loading-matlab-mat-data-in-python

In [8]:
# Similarly we have
#scipy.io.loadmat("averageFunc.m")
variables = scipy.io.loadmat('data.mat', squeeze_me=True)
variables

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Fri Feb  8 01:20:47 2019',
 '__version__': '1.0',
 '__globals__': [],
 'a': array([[1, 2, 3],
        [4, 5, 6]], dtype=uint8),
 'S': array((array([[ 7,  8,  9],
        [10, 11, 12]], dtype=uint8),), dtype=[('b', 'O')]),
 'M': array([(array([[ 2,  4,  6],
        [ 8, 10, 12]], dtype=uint8),),
        (array([[ 1,  3,  5],
        [ 7,  9, 11]], dtype=uint8),)], dtype=[('c', 'O')])}

In [11]:
a = variables['a'] # array
S = variables['S'] # structure containing an array
M = variables['M'] # array of structures

a

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [12]:
S

array((array([[ 7,  8,  9],
       [10, 11, 12]], dtype=uint8),), dtype=[('b', 'O')])

In [13]:
M

array([(array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=uint8),),
       (array([[ 1,  3,  5],
       [ 7,  9, 11]], dtype=uint8),)], dtype=[('c', 'O')])