# Python helper file/script for MATLAB

This cell sets up the notebook to import numpy, datascience, seaborn, pandas, matplotlib etc.

In [1]:
# Run this cell to set up the notebook.

# These lines import the Numpy, Datascience, pandas modules.
import numpy as np
import pandas as pd
import seaborn as sns
from datascience import *
import random
import matplotlib
import matplotlib.pyplot as plt

# Importing plotting libraries and styles
%matplotlib inline
plt.style.use('fivethirtyeight')

# For Pandas to ignore FutureWarning displays
import warnings
warnings.simplefilter('ignore', FutureWarning)

### The cell given below sets up MATLAB for the notebook
Source: https://sehyoun.com/blog/20180904_using-matlab-with-jupyter-notebook.html

In [17]:
import matlab.engine
import io
import scipy.io
from IPython.core.magic import register_cell_magic
ip = get_ipython()

out = io.StringIO()
err = io.StringIO()

# Setup matlab cell magic #
@register_cell_magic
def matlab_magic(line,cell):
    out.truncate(0)
    out.seek(0)
    err.truncate(0)
    err.truncate(0)
    raw = '''{line}.eval("""{cell}""", nargout=0, stdout=out, stderr=err)'''
    ip.run_cell(raw.format(line=line, cell=cell))
    print(out.getvalue())
    print(err.getvalue())
    
# Starting a MATLAB engine called eng
eng = matlab.engine.start_matlab()

In [18]:
%%matlab_magic eng

t = linspace(0,6*pi,100);
plot(sin(t))
grid on
hold on
plot(cos(t), 'r')

In [4]:
%%matlab_magic eng

x = 5;
disp(x);
x

     5


x =

     5





Calling another MATLAB file from Python script

In [5]:
%%matlab_magic eng

my_array = [10, 20, 30, 40, 50]
avgOfThis = averageFunc(my_array)


my_array =

    10    20    30    40    50


avgOfThis =

    30





**Python to MATLAB**

Source: https://stackoverflow.com/questions/10997254/converting-numpy-arrays-to-matlab-and-vice-versa

In [6]:
x = [1,2,3]
y = "hello"
z = [[1,2,3], [4,5,6]]

scipy.io.savemat('test.mat', dict(x=x, y=y, z=z))

In [7]:
%%matlab_magic eng
load test
x
y
z


x =

  1x3 int64 row vector

   1   2   3


y =

    'hello'


z =

  2x3 int64 matrix

   1   2   3
   4   5   6





**MATLAB to Python**

Source: http://www.blogforbrains.com/blog/2014/9/6/loading-matlab-mat-data-in-python

In [8]:
# Similarly we have
#scipy.io.loadmat("averageFunc.m")
variables = scipy.io.loadmat('data.mat', squeeze_me=True)
variables

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Fri Feb  8 01:20:47 2019',
 '__version__': '1.0',
 '__globals__': [],
 'a': array([[1, 2, 3],
        [4, 5, 6]], dtype=uint8),
 'S': array((array([[ 7,  8,  9],
        [10, 11, 12]], dtype=uint8),), dtype=[('b', 'O')]),
 'M': array([(array([[ 2,  4,  6],
        [ 8, 10, 12]], dtype=uint8),),
        (array([[ 1,  3,  5],
        [ 7,  9, 11]], dtype=uint8),)], dtype=[('c', 'O')])}

In [9]:
a = variables['a'] # array
S = variables['S'] # structure containing an array
M = variables['M'] # array of structures

a

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [10]:
S

array((array([[ 7,  8,  9],
       [10, 11, 12]], dtype=uint8),), dtype=[('b', 'O')])

In [11]:
M

array([(array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=uint8),),
       (array([[ 1,  3,  5],
       [ 7,  9, 11]], dtype=uint8),)], dtype=[('c', 'O')])

In [21]:
# Adds the MMB.m as well as MMBOPT1.m and MMBOPT2.m folders to the MATLAB engine path"
eng.addpath(r'/Users/Desktop/monetaryPolicy/mmb-gui-mlab/2.3.2', nargout=0)
eng.addpath(r'/Users/Desktop/monetaryPolicy/mmb-gui-mlab/2.3.2/MMB_OPTIONS', nargout=0)

In [26]:
testexcel = pd.read_excel("../mmb-gui-mlab-2.3.2/OUTPUT/results.xls", sheetname = "all IRFs Mon. Pol. Shock")

In [28]:
headers = testexcel.iloc[0]
new_df  = pd.DataFrame(testexcel.values[1:], columns=headers)

In [29]:
new_df

0   wtilde_t           0 -0.00699479279334547 -0.005762796029070893  \
0   lambda_zstar_t     0          -0.00019142            0.00374196   
1   m_t                0          -0.00640682             -0.628739   
2   pi_t               0           0.00640682            0.00458512   
3   x_t                0            -0.617748              0.587575   
4   s_t                0             0.204864            -0.0129795   
5   i_t                0          -0.00435076           -0.00799692   
6   h_t                0          -0.00772508             -0.042797   
7   kbar_t1            0          -0.00013688          -0.000384165   
8   q_t                0            -0.874481            -0.0381261   
9   ytilde_t           0          -0.00475476            -0.0277619   
10  R_t                0             0.251808           0.000651745   
11  mutilde_t          0          -0.00242847           -0.00553389   
12  rhotilde_t         0             0.133842            -0.0269679   
13  u_t                0            0.0663141            -0.0133617   
14  x_M_t              0                    0                     0   
15  eps_M_t            0                    0                     0   
16  mu_z_t             0          3.82335e-18           1.07665e-16   
17  eps_muz_t          0                    0                     0   
18  x_z_t              0                    0                     0   
19  mu_ups_t           0          5.41368e-19          -3.46924e-17   
20  eps_muups_t        0                    0                     0   
21  x_ups_t            0                    0                     0   
22  cf_t               0          2.80671e-16            6.2047e-16   
23  wtildef_t          0         -1.74697e-16           5.43379e-17   
24  lambda_zstarf_t    0          1.07733e-16           1.32205e-16   
25  mf_t               0         -8.93893e-17          -5.70756e-16   
26  pif_t              0          8.35912e-17            1.0672e-16   
27  xf_t               0                    0          -2.79053e-34   
28  sf_t               0         -3.64889e-17             2.635e-16   
29  if_t               0         -8.52533e-16          -1.10127e-15   
..                ... ..                  ...                   ...   
37  uf_t               0         -4.23741e-17           2.03326e-16   
38  epsilon_t          0         -5.31052e-19          -5.18679e-19   
39  interest           0              1.00723            0.00260698   
40  inflation          0           0.00640682             0.0109919   
41  inflationq         0            0.0256273             0.0183405   
42  outputgap          0          -0.00475476            -0.0277619   
43  output             0          -0.00475476            -0.0277619   
44  AUX_ENDO_LEAD_75   0            0.0183405             0.0130968   
45  AUX_ENDO_LEAD_79   0            0.0130968            0.00921613   
46  AUX_ENDO_LEAD_83   0           0.00921613            0.00616021   
47  AUX_ENDO_LEAD_110  0           -0.0277619            -0.0219998   
48  AUX_ENDO_LEAD_114  0           -0.0219998            -0.0173575   
49  AUX_ENDO_LEAD_118  0           -0.0173575            -0.0136148   
50  AUX_ENDO_LEAD_145  0           -0.0277619            -0.0219998   
51  AUX_ENDO_LEAD_149  0           -0.0219998            -0.0173575   
52  AUX_ENDO_LEAD_153  0           -0.0173575            -0.0136148   
53  AUX_ENDO_LAG_4_1   0                    0            0.00640682   
54  AUX_ENDO_LAG_4_2   0                    0          -4.16267e-17   
55  AUX_ENDO_LAG_45_1  0                    0           -0.00475476   
56  AUX_ENDO_LAG_45_2  0                    0                     0   
57  AUX_ENDO_LAG_45_3  0                    0                     0   
58  AUX_ENDO_LAG_44_1  0                    0           -0.00475476   
59  AUX_ENDO_LAG_44_2  0                    0                     0   
60  AUX_ENDO_LAG_44_3  0                    0                     0   
61  AUX_ENDO_LAG_41_1  0